from __future__ import annotations

OPERATING_MODES = {
    "sim": {
        "label": "SIM",
        "description": "Continuous scanning with simulated transaction logic and isolated virtual accounts. No real orders.",
        "execution": "simulated",
        "available": True,
    },
    "live": {
        "label": "LIVE",
        "description": "Real venue balances, orders and hedging. Intentionally locked until LIVE execution is implemented and validated.",
        "execution": "real",
        "available": False,
    },
}


DEFAULT_CONFIG = {
    # v0.8.30 canonical account/balance model.  MONITOR uses the virtual ledger;
    # LIVE is read-only account state until real execution is explicitly unlocked.
    "account_currency": "GBP",
    "account_balance_stale_seconds": 90,
    "account_refresh_seconds": 30,
    "account_history_cache_seconds": 120,
    "account_reconciliation_tolerance": 0.01,
    # 0.9.8: provider-derived LIVE-context decisions are evidence only.
    "live_decision_evidence_enabled": True,
    # Provider market-feed entitlement is independent from SIM/LIVE economics.
    # Requested and runtime-effective Betfair feed states are intentionally distinct.
    "betfair_feed_entitlement": "delayed",
    "smarkets_enabled": True,
    "smarkets_api_access_state": "awaiting_api_access",
    "live_decision_max_quote_age_seconds": 10.0,
    "live_decision_max_receipt_spread_ms": 1500,
    "live_decision_min_mapping_confidence": 0.72,
    # Explicit extra SIM venue capital. New providers never inherit or redistribute existing bankroll.
    "sim_provider_starting_balances": {},
    "scanner_enabled": True,
    # 0.9.36 engine runtime resource guard. Architecture remains open-ended, but
    # one evaluation fan-out is bounded so experiments cannot starve scanner work.
    "engine_max_concurrent_runtimes": 100,
    "scan_interval_seconds": 60,  # legacy alias for discovery cadence
    "discovery_interval_seconds": 60,
    "price_scan_tick_seconds": 2,
    "price_refresh_inplay_seconds": 2,
    "price_refresh_near_seconds": 3,
    "price_refresh_today_seconds": 8,
    "price_refresh_later_seconds": 30,
    "price_quote_max_age_seconds": 10.0,
    "price_scan_cache_limit": 1000,
    # v0.8.44 bounded quote storage. Fast scans keep one latest raw quote per
    # runner/side and compact hourly counts; legacy append-only rows are pruned
    # incrementally so storage remains stable as scan volume increases.
    "snapshot_legacy_keep_rows": 100000,
    "snapshot_prune_batch_rows": 100000,
    "snapshot_maintenance_seconds": 10,
    "settlement_poll_seconds": 30,
    "horizon_hours": 24,
    "minimum_liquidity": 2.0,
    "minimum_net_roi_pct": 1.0,
    "minimum_profit": 0.0,
    "event_match_threshold": 0.72,
    "max_bankroll_pct": 100.0,
    "max_event_exposure_pct": 100.0,
    "one_recommendation_per_market": True,
    "require_cross_exchange": True,
    "hide_demo_data": True,
    "beginner_mode": True,
    "quality_reference_bankroll": 500.0,
    "stale_quote_seconds": 90.0,
    "research_1x2_enabled": True,
    "research_two_way_enabled": True,
    "research_multi_runner_enabled": True,
    "racing_greyhounds_enabled": True,
    "racing_minimum_liquidity": 2.0,
    "racing_minimum_net_roi_pct": 1.0,
    "racing_minimum_profit": 0.0,
    "racing_match_threshold": 0.90,
    "racing_runner_match_threshold": 0.92,
    "racing_monitor_enabled": True,
    "racing_monitor_betfair_starting_balance": 250.0,
    "racing_monitor_matchbook_starting_balance": 250.0,
    "racing_minimum_quality_band": "Tiny",
    "racing_execution_max_stake": 25.0,
    "racing_max_event_exposure_pct": 100.0,
    "racing_execution_max_slippage_pct": 0.50,
    "racing_execution_max_unhedged_exposure": 25.0,
    "racing_execution_hedge_reserve_pct": 20.0,
    # 0.9.3 Racing-only controlled re-arm after transient MONITOR misses.
    "racing_monitor_retry_cooldown_seconds": 5.0,
    "racing_monitor_max_attempts_per_race": 3,
    # Optional 0 disables skew rejection while still recording receipt-time spread.
    "racing_max_cross_venue_receipt_spread_ms": 0,
    # 0.9.3 bounded matched-market diagnostics. Current state/rollups remain;
    # repetitive verbose evaluations expire incrementally without automatic VACUUM.
    "matched_market_retention_hours": 48,
    "matched_market_prune_batch_rows": 5000,
    "matched_market_heartbeat_seconds": 900,
    "matched_market_maintenance_seconds": 30,
    # 0.9.36 archival remains disabled by default. When the archive pilot is ON,
    # raw-row pruning pauses until archive-gated pruning is explicitly armed.
    "matched_market_archive_enabled": False,
    "matched_market_archive_runtime_gate_required": True,
    "matched_market_archive_required_before_prune": False,
    "matched_market_archive_safety_pause_seconds": 3600,
    "matched_market_archive_failure_backoff_seconds": 1800,
    "matched_market_archive_catchup_delay_seconds": 30,
    "matched_market_archive_nice": 10,
    "live_lookback_hours": 8,
    "sport_football_enabled": True,
    "sport_tennis_enabled": True,
    "sport_darts_enabled": True,
    "sport_snooker_enabled": True,
    "sport_basketball_enabled": True,
    "sport_american_football_enabled": True,
    "sport_baseball_enabled": True,
    "sport_ice_hockey_enabled": True,
    "sport_cricket_enabled": True,
    "sport_rugby_union_enabled": True,
    "sport_rugby_league_enabled": True,
    "sport_volleyball_enabled": True,
    "sport_handball_enabled": True,
    "sport_australian_rules_enabled": True,
    "sport_field_hockey_enabled": True,
    "alerts_enabled": True,
    "alert_quality_bands": ["Usable", "Strong", "Excellent"],
    "alert_min_deployed_roi_pct": 0.75,
    "alert_min_bankroll_roi_pct": 0.0,
    "alert_min_capital_used_pct": 0.0,
    "alert_min_profit": 1.0,
    "alert_quality_improvements": True,
    "alert_sound": True,
    "alert_retry_minutes": 15,
    "matchbook_enabled": True,
    "matchbook_username": "",
    "matchbook_commission_pct": 2.0,
    "betfair_enabled": True,
    "betfair_commission_pct": 2.0,  # fallback only if API market rate is unavailable
    "execution_plan_ttl_ms": 1500,
    "execution_max_stake": 25.0,
    "execution_max_slippage_pct": 0.50,
    "execution_max_unhedged_exposure": 25.0,
    "execution_hedge_reserve_pct": 20.0,
    "execution_balance_tolerance": 0.10,
    "execution_pre_match_only": True,
    # v0.8.30: optional MONITOR-only multi-tranche scaling. Disabled by default.
    "pre_match_monitor_enabled": True,
    "inplay_monitor_enabled": True,
    "inplay_betfair_delay_ms": 5000,
    "inplay_matchbook_delay_ms": 1000,
    "inplay_adverse_odds_pct_per_second": 0.20,
    "inplay_liquidity_decay_pct_per_second": 8.0,
    "inplay_execution_max_slippage_pct": 1.50,
    "inplay_monitor_cooldown_seconds": 8.0,
    "monitor_timing_checkpoints_ms": [100, 250, 500, 1000],
    "monitor_timing_reference_checkpoint_ms": 250,
    "monitor_timing_max_concurrent_runs": 6,
    "monitor_execution_checkpoint_ms": 500,
    "monitor_hedge_checkpoint_ms": 1000,
    # Legacy shared Monitor defaults are retained for backward compatibility only.
    "monitor_betfair_starting_balance": 250.0,
    "monitor_matchbook_starting_balance": 250.0,
    # v0.7.24: independent Monitor portfolio balances and strategy/risk controls.
    "pre_match_monitor_betfair_starting_balance": 250.0,
    "pre_match_monitor_matchbook_starting_balance": 250.0,
    "inplay_monitor_betfair_starting_balance": 250.0,
    "inplay_monitor_matchbook_starting_balance": 250.0,
    "pre_match_minimum_liquidity": 2.0,
    "pre_match_minimum_net_roi_pct": 1.0,
    "pre_match_minimum_profit": 0.0,
    "pre_match_minimum_quality_band": "Tiny",
    "pre_match_execution_max_stake": 25.0,
    "pre_match_max_event_exposure_pct": 100.0,
    "pre_match_execution_max_slippage_pct": 0.50,
    "pre_match_execution_max_unhedged_exposure": 25.0,
    "pre_match_execution_hedge_reserve_pct": 20.0,
    "inplay_minimum_liquidity": 2.0,
    "inplay_minimum_net_roi_pct": 1.0,
    "inplay_minimum_profit": 0.0,
    "inplay_minimum_quality_band": "Tiny",
    "inplay_execution_max_stake": 25.0,
    "inplay_max_event_exposure_pct": 100.0,
    "inplay_execution_max_unhedged_exposure": 25.0,
    "inplay_execution_hedge_reserve_pct": 20.0,
    "display_profile": "auto",
}
